config/routes.rb
Drafterize::Application.routes.draw do

  
  resources :drafts do 
    resources :players
  end
  
  devise_for :users
  root to: 'welcome#index'
end

app/models/draft.rb
class Draft < ActiveRecord::Base
  has_many :teams
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team

  after_create :update_draft_counters

  private

  def update_draft_counters
    draft = team.draft
    
    if draft.current_round.odd?
      if draft.team_position == draft.teams.count
        draft.current_round += 1
      else
        draft.team_position += 1 
      end
    else
      if draft.team_position == 1
        draft.current_round += 1
      else
        draft.team_position -= 1
      end
    end

    draft.save
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  belongs_to :draft
  has_many :players
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
   
     protected
   
     def configure_permitted_parameters
       devise_parameter_sanitizer.for(:sign_up) << :name
     end
end

app/controllers/drafts_controller.rb
class DraftsController < ApplicationController

  def show
    @draft = Draft.find(params[:id])
  end

  def new
    #if current_user
      #@draft = Draft.new
    #else
      #raise Pundit::NotAuthorizedError, "You must be logged in to create a new list."
    #end
  end

  def create
    # create draft
    @draft = Draft.new(params.require(:draft).permit(:name, :rounds, :num_of_minutes))
    # loop through teams submitted
    if @draft.save
      params[:team_name].each do |team_name|
        # create teams (check out accepts_nested_attributes_for)
        Team.create(name: team_name, draft: @draft) unless team_name.blank?       
      end
      flash[:notice] = "Draft created"
      redirect_to @draft
    else
      flash[:error]= "Unable to create draft"
      render :new
    end
      
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_draft
  def create
    @player = Player.new(params.require(:player).permit(:name))
     
    drafting_team = @draft.teams[@draft.team_position - 1]
    @player.team = drafting_team

    if @player.save 
      flash[:notice] = "#{@player.name} added to #{drafting_team.name}"
    else
      flash[:error] = "There was a problem saving this player"
    end

    redirect_to @draft
  end

  private

  def set_draft
    @draft = Draft.find(params[:draft_id])
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drafts_helper.rb
module DraftsHelper
  def render_player_name_for_team_and_round(team, round)
    Rails.logger.info ">>>> Draft: #{team.draft.inspect}"
    Rails.logger.info ">>>> TEam: #{team.inspect}"
    Rails.logger.info ">>> players: #{team.players.inspect}"
    player = team.players.where(round: round).first
    Rails.logger.info ">>>> Player: #{player.inspect}"
    player ? player.name : ""
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/drafts/_form.html.erb
<%= form_for Draft.new do |f| %>
  <div class="form-group">
    <%= f.label :name, "Draft Name" %>
    <%= f.text_field :name, placeholder: "Enter Draft Name", class: "form-control" %>
  </div>
  <p class="roundss"><b>Choose # of rounds:</b></p>
  <%= f.select :rounds, options_for_select(["10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"]), {}, {class: "form-control"} %>
 
  <p class="minutess"><b>Choose minutes per pick:</b></p>
  <%= f.select :minutes_per_round, options_for_select(["0.5", "1.0", "1.5", "2.0", "2.5", "3.0", "3.5", "4.0", "4.5", "5.0"]), {}, {class: "form-control"} %>

  <p class="teamnames"><b>Enter Team Names (in order of draft pick):</b></p>
  
  <% 10.times do %>
    <%=  render "team_name_form" %>
  <% end %>
  <div class="buttonn">
    <%= f.submit "Start Draft", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/drafts/_team_name_form.html.erb
<div class="form-group">
  <%= text_field_tag "team_name[]", nil, class: "form-control", placeholder: "Enter Team Name" %>
</div>

app/views/drafts/new.html.erb
<div class="newform">
  <h1 class="nd">New Draft</h1>
    <div class="formm">
      <h3>Guidelines:</h3>
      <ul>
        <li>Make a name for the draft</li>
        <li>Pick the number of rounds you want</li>
        <li>Choose how long each person has to pick</li>
        <li>Add the number of teams that there are</li>
        <li>Add the names of each team in order of draft pick they have</li>
      </ul>
    </div>
      <div class="draftform">
        <%= render partial: 'form', locals: {draft: @draft} %>
      </div>
    </div>
</div>

app/views/drafts/show.html.erb
<h1><%= @draft.name %></h1>
<%= form_for [@draft, Player.new] do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "Draft" %>
<% end %>

<table class="table table-bordered">
  <thead>
    <th></th>
    <% @draft.teams.each do |team| %>
      <th><%= team.name %></th>
    <% end %>
  </thead>
  <tbody>
    <% @draft.rounds.times do |round| %>
      <tr>
        <td><%= round + 1 %></td> 
        <% @draft.teams.each do |team| %>
          <td id="round-<%= round %>-team-<%= team.id %>">
            <%= render_player_name_for_team_and_round(team, round + 1) %>
          </td>
        <% end %>
      </tr>    
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drafterize</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Draft", new_draft_path %></li>

        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
      </ul>

      <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
      <% elsif flash[:error] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:error] %>
       </div>
      <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
      <% end %>
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/create.js.erb
$("#round-<%= @draft.current_round %>-team-<%= @draft.current_position %>").html("<%= @player.name %>");

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <div class="row">
    <div class="col-md-6">
      <h1>DRAFTERIZE</h1>
      <p>The online tool for your offline draft!</p>
      <p>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
      </p>
      <h2 class="one">No more white boards!</h2>
      <h3>No more stopwatches!</h3>
      <h4>Fully automated!</h4>
      <h5>Unlimited drafts!</h5>
      <h6>Unlimited fun!</h6>
      <p class="ndb"><%= link_to "New Draft", new_draft_path, class: 'btn btn-primary' %></p>
    </div>
    <div class="col-md-6">
      <p class="img">
        <%= image_tag 'ff2.png' %>
      </p>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
  </div>
  <div class="col-md-4">
    <h1>Sign Up For A Free Account Today!</h1>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-4">
  </div>
</div>